# docker-compose.yml

version: "3.8"

services:
  server:
    build:
      context: ./server
    restart: always
    ports:
      - 6000:8080
    networks:
      - db-net
    depends_on:
      - db
  db:
    image: mysql:8.0.39
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersaiyan
    networks:
      - db-net
    ports:
      - 6001:80

networks:
  db-net: